version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.kie:kie-api
    versions:
    - 7.49.0.Final
    - 7.49.0.t20210118
    - 7.50.0.Final
    - 7.50.0.t20210209
    - 7.51.0.Final
    - 7.51.0.t20210303
    - 7.52.0.Final
    - 7.52.0.t20210322
  - dependency-name: org.kie:kie-internal
    versions:
    - 7.49.0.Final
    - 7.49.0.t20210118
    - 7.50.0.Final
    - 7.50.0.t20210209
    - 7.51.0.Final
    - 7.51.0.t20210303
    - 7.52.0.Final
    - 7.52.0.t20210322
  - dependency-name: org.kie:kie-maven-plugin
    versions:
    - 7.48.0.Final
    - 7.49.0.Final
    - 7.50.0.Final
    - 7.51.0.Final
    - 7.52.0.Final
  - dependency-name: org.optaplanner:optaplanner-persistence-jaxb
    versions:
    - 8.1.0.Final
    - 8.2.0.Final
    - 8.3.0.Final
    - 8.4.0.Final
    - 8.4.1.Final
  - dependency-name: org.optaplanner:optaplanner-core
    versions:
    - 8.1.0.Final
    - 8.2.0.Final
    - 8.3.0.Final
    - 8.4.0.Final
    - 8.4.1.Final
  - dependency-name: com.thoughtworks.xstream:xstream
    versions:
    - 1.4.15
